id:
  name: id
  in: path
  description: entity id
  required: true
  schema:
    type: integer
interview_id:
  name: interview_id
  in: path
  description: Interview id
  required: true
  schema:
    type: integer
token:
  name: token
  in: path
  description: token
  required: true
  schema:
    type: string
vacancy_token:
  name: token
  in: path
  description: Vacancy public url token
  required: true
  schema:
    type: string
response_token:
  name: token
  in: path
  description: Response public url token
  required: true
  schema:
    type: string
pagination_page:
  name: page
  in: query
  description: page number
  required: false
  schema:
    type: integer
    default: 1
pagination_page_size:
  name: limit
  in: query
  description: page size
  required: false
  schema:
    type: integer
    default: 20
sort_order:
  name: sort[order]
  in: query
  description: sort order
  required: false
  schema:
    type: string
    default: 'desc'
    enum: [ 'asc', 'desc' ]
filter_id:
  name: filter[id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_active:
  name: filter[active]
  in: query
  required: false
  schema:
    type: boolean
filter_response_id:
  name: filter[response_id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_user_id:
  name: filter[user_id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_vacancy_id:
  name: filter[vacancy_id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_vacancy_user_id:
  name: filter[vacancy][user_id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_response_status_id:
  name: filter[response_status_id]
  in: query
  required: false
  schema:
    oneOf:
      - type: integer
      - type: array
        items:
          type: integer
filter_created_at_from:
  name: filter[created_at][from]
  in: query
  required: false
  schema:
    type: string
    format: date-time
filter_created_at_to:
  name: filter[created_at][to]
  in: query
  required: false
  schema:
    type: string
    format: date-time
filter_company_id:
  name: filter[company_id]
  in: query
  required: false
  type: integer
filter_enumeration_id:
  name: filter[enumeration_id]
  in: query
  required: true
  type: integer
filter_is_file:
  name: filter[is_file]
  in: query
  description: Filter by resumes uploaded as files
  required: false
  schema:
    type: boolean